### ISSUE TITLE
기능 구현 Todo List / Section - magic_card (마법 부여 최저가 검색)

### ISSUE THREAD

**Issue by elniakim** [elniakim/dnfnow#5]
- [ ] 부위 선택 / 카드 속성 선택 하는 listbox 만들어서 리스트 띄우기
- [ ] 각 listbox에 해당하는 카드 리스트 만들기
- [ ] 카드별 구매 가격 및 동일 성능에 대해서는 가장 싼 카드에 bold
- [ ] 선택한 listbox에 대해서는 그 성능을 오름차순으로 정렬해서 보여주기 (같은 성능은 같은 칸 으로)
- [ ] 모든 카드는 일시에 업데이트를 해야하고, gevent를 이용해서 parallel하게 업데이트 하도록 할 것 (최대 1분)

**Comment by elniakim** [comment]
Self due-date: 2018.10.31
